name: Android CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    
env:
  version: 'v1.24.0-test'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - uses: ilharp/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDir: app/build/outputs/apk/release
        signingKey: ${{ secrets.SIGNING_KEY }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        buildToolsVersion: 33.0.0
    #- name: Grant execute permission for gradlew
    #  run: chmod +x gradlew
    - name: Build with Gradle
    #  run: ./gradlew build
    - uses: gradle/gradle-build-action@v2
    - run: gradle assembleRelease
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: WBUpdater APK
        path: app/build/outputs/apk/release/*.apk
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: "${{ env.version }}"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.version }}"
        files: app/build/outputs/apk/release/*.apk
        prerelease: false
