name: Android CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  version: 'v24.1.0-beta'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    #- name: Grant execute permission for gradlew
    #  run: chmod +x gradlew
    - name: Build with Gradle
    #  run: ./gradlew build
      uses: gradle/gradle-build-action@v2
    - run: gradle assembleRelease
    - name: Sign app APK
      uses: ilharp/sign-android-release@v1
      id: sign_app
      with:
        releaseDir: app/build/outputs/apk/release
        signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
        keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        buildToolsVersion: 33.0.0
    - uses: jungwinter/split@v2
      id: signed_files
      with:
        msg: ${{ steps.sign_app.outputs.signedFiles }}
        separator: ':'
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: WBUpdater APK
        path: ${{steps.sign_app.outputs.signedFile}} #app/build/outputs/apk/debug/*.apk
        if-no-files-found: warn
        retention-days: 90
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: "${{ env.version }}"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.version }}"
        files: |
          ${{ steps.signed_files.outputs._0 }}
          ${{ steps.signed_files.outputs._1 }}
          ${{ steps.signed_files.outputs._2 }}
          ${{ steps.signed_files.outputs._3 }}
          ${{ steps.signed_files.outputs._4 }} #app/build/outputs/apk/debug/*.apk 
        prerelease: true
